### ISSUE TITLE
Streaming stops after the app entered background

### ISSUE THREAD

**Issue by ryo0126** [aws-samples/amazon-ivs-broadcast-for-ios-demo#18]
Hi. I'm using this sample app and I've noticed that streaming stops when the app enters the background.
This seems to be unexpected behavior, because the app creates a background image before streaming in a method `BroadcastViewModel.createAppBackgroundImageSource()`.

I believe the expected behavior is as follows:
When the app is in the background, it streams the static background image that is set up in `BroadcastViewModel.createAppBackgroundImageSource()`.

## Environment
Xcode: 14.2
iPhone 13 (physical device)
iOS 16.0

## Demo app version
Latest commit in main branch: `f3e3fad895694cc4254d333a625621c8be80c5a5`

## Amazon IVS SDK Version

AmazonIVSBroadcast 1.10.0

## What I changed

* Update signing.
* Remove App group from Capabilities
* Update ingest server and stream key (at line 16, 17 of `Helpers/Constants.swift` )

## How to reproduce

1. PC: Set ingest server and stream key in `Helpers/Constants.swift`.
2. PC: Build the app.
3. iPhone: Launch the app.
4. iPhone: Start streaming by tapping the Start button.
5. PC: Open playback URL to watch the stream.
6. iPhone: Move the app to the background.

Result: The stream will stop after about 10 seconds.

## What is unexpected?

Streaming stops after the app entered the background, as mentioned in `How to reproduce`.

## What is expected?

* The app will continue streaming when it's in the background.
* The app will stream a static background image that is set up in `BroadcastViewModel.createAppBackgroundImageSource()`, while it's in the background

**Comment by bclymer** [comment]
Hi @ryo0126 , in order for the background video feature to work, you must have an actively recording microphone and have the background audio entitlement enabled for your app. Without those two requirements being met, iOS will suspend your app's process.

There is a bug in the SDK that if our `IVSMicrophone` is attached after the `createAppBackgroundImageSource` is called, it won't broadcast in the background as expected. So please make sure you attach our microphone before calling that API.

Let me know if all of those requirements are already met in your app, and if so, please provide some sample code that could help us reproduce the issue.

**Comment by ryo0126** [comment]
@bclymer 
> There is a bug in the SDK that if our IVSMicrophone is attached after the createAppBackgroundImageSource is called, it won't broadcast in the background as expected. So please make sure you attach our microphone before calling that API.

The app successfully streams the image while it is in the background after I changed the code to attach the microphone before calling this API.
Thank you very much.
